### ISSUE TITLE
crash on startup on version 1.11.2

### ISSUE THREAD

**Issue by ARatfat** [al132/Alchemistry#2]
Hello, 

I report this crash on startup https://pastebin.com/7SNzDDQD. 
I've alchemistry 0.5.5
& forgelin 1.4.2

Best Regards

**Comment by KristjanKr** [comment]
I second this crash https://paste.ee/p/DOpXi

**Comment by KristjanKr** [comment]
Exactly same setup using latest forge build 2298

**Comment by al132** [comment]
Huh, interesting. For some reason I was only able to duplicate this outside of the development environment. Anyway, thanks for the heads up; i've uploaded a hotfix on curse https://minecraft.curseforge.com/projects/alchemistry/files/2421125
