### ISSUE TITLE
[1.11.2- 0.5.6] - Server Crash on startup!

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [al132/Alchemistry#3]
Loads perfectly on client just on the server!

Hello by the way Al o/

https://pastebin.com/fAGPW302

**Comment by EmosewaGamer** [comment]
Yup, I got the same crash.

**Comment by al132** [comment]
Thanks for letting me know. I never actually tested to see if the mod would startup properly on a server now that I think about it. Anyway, I got this fixed up right away and v0.5.7 should show up on curse soon.
