### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 0dikpah** [al132/Alchemistry#4]
(Latest forge for mc 1.11.2)
(Latest mod version)
(singleplayer)
[crash-2017-05-21_17.01.00-client.txt](https://github.com/al132/Alchemistry/files/1017109/crash-2017-05-21_17.01.00-client.txt)

**Comment by al132** [comment]
I just uploaded v0.5.8 which should fix this issue. (Also, note: the mod now depends on ATM Lib as well) https://minecraft.curseforge.com/projects/alchemistry/files/2422697
